# Generated by Django 4.2.1 on 2024-07-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=100, verbose_name='Вид')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='Пол')),
                ('breed', models.CharField(max_length=200, verbose_name='Порода')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'db_table': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='ImagePets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='PetPics', verbose_name='Изображение')),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Animals.animals')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'Изображения животных',
            },
        ),
    ]
