# Generated by Django 4.2.1 on 2024-09-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeAnimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_title', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Категория')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, verbose_name='Максимальный возраст')),
            ],
            options={
                'verbose_name': 'Возраст',
                'verbose_name_plural': 'Возраст',
                'db_table': 'Возраст',
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'db_table': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_title', models.CharField(max_length=100, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'db_table': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='TypeAnimals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=200, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'Тип',
            },
        ),
        migrations.CreateModel(
            name='ImagePets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='petpics', verbose_name='Изображение')),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='animals.animals', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'Изображения животных',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_title', models.CharField(max_length=200, unique=True, verbose_name='Порода')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_type', to='animals.typeanimals', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'db_table': 'Порода',
            },
        ),
        migrations.AddField(
            model_name='animals',
            name='breed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='breed_pet', to='animals.breed', verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='animals',
            name='gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gender_pet', to='animals.gender', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='animals',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type_pet', to='animals.typeanimals', verbose_name='Тип'),
        ),
    ]
