# Generated by Django 4.2.1 on 2024-09-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ageanimals',
            old_name='age_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='breed_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='gender_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='typeanimals',
            old_name='type_title',
            new_name='title',
        ),
    ]
