# Generated by Django 4.2.1 on 2024-08-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_imagepets_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepets',
            name='pet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='animals.animals'),
        ),
    ]
